export const LOAD_USERS = "LOAD_USERS";
export const LOAD_QUESTIONS = "LOAD_QUESTIONS";
export const SET_ACTIVE_USER = "SET_ACTIVE_USER";
export const ADD_QUESTION = "ADD_QUESTION";
export const ADD_QUESTION_ANSWER = "ADD_QUESTION_ANSWER";